=== seolanijn/Level_4/C#/PasswordManager/account_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for PasswordManager",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "Description",
    "UserId",
    "Password"
  ],
  "properties": {
    "Description": {
      "Explanation": "A description of the online account",
      "type": "string"
    },
    "UserId": {
      "Explanation": "User's identifier for logging-in",
      "type": "string"
    },
    "LoginUrl": {
      "Explanation": "Web address of the account's log-in page",
      "type": "string",
      "format": "uri"
    },
    "AccountNum": {
      "Explanation": "The account number for the user's online account",
      "type": "string"
    },
    "Password": {
      "Explanation": "Information related specifically to the password",
      "type": "object",
      "required": [
        "Value",
        "StrengthNum",
        "StrengthText"
      ],
      "properties": {
        "Value": {
          "description": "User's password for logging-in",
          "type": "string"
        },
        "StrengthNum": {
          "description": "Indicates how secure the password is",
          "type": "integer",
          "minimum": 0,
          "maximum": 100
        },
        "StrengthText": {
          "description": "Indicates how secure the password is",
          "type": "string",
          "enum": [
            "very weak",
            "weak",
            "good",
            "strong",
            "very strong"
          ]
        },
        "LastReset": {
          "description": "Date the password was last updated",
          "type": "string"
        }
      }
    }
  }
}

=== seolanijn/Level_4/C#/PasswordManager/account_data.json
[
  {
    "Description": "Disney Plus",
    "UserId": "dpplus",
    "LoginUrl": "https://www.disneyplus.com/login",
    "AccountNum": "1001",
    "Password": {
      "Value": "dis2y+",
      "StrengthNum": 48,
      "StrengthText": "good",
      "LastReset": "2022-05-20"
    }
  },
  {
    "Description": "W3Schools Online Web Tutorials",
    "UserId": "wwwschools3",
    "LoginUrl": "https://profile.w3schools.com/log-in",
    "AccountNum": "1002",
    "Password": {
      "Value": "w3sOwt333",
      "StrengthNum": 84,
      "StrengthText": "very strong",
      "LastReset": "2022-05-21"
    }
  },
  {
    "Description": "Crave",
    "UserId": "cravvve123",
    "LoginUrl": "https://www.crave.ca/en",
    "AccountNum": "1003",
    "Password": {
      "Value": "creative123",
      "StrengthNum": 66,
      "StrengthText": "strong",
      "LastReset": "2022-05-22"
    }
  },
  {
    "Description": "Apple TV+",
    "UserId": "appleTVP",
    "LoginUrl": "https://tv.apple.com/ca",
    "AccountNum": "1004",
    "Password": {
      "Value": "ApplePlusTV123",
      "StrengthNum": 94,
      "StrengthText": "very strong",
      "LastReset": "2022-05-23"
    }
  }
]
